set Cache-Control header in 304 Not Modified response case as well.
zopefoundation/Products.CMFCore pull request #111
Opened 2021-03-31 09:45 UTC by fdiary

Currently, responses of several CMFCore types do not have Cache-Control header based on Caching Policy Manager in '304 Not Modified' response case. Imagine the following scenario with intermediate cache server (like Apache Traffic Server) : 

* intermediate cache server fetches from Zope and store it in its cache.
* we modify Caching Policy Manager configuration.
* intermediate cache server tries to revalidate its cache with 'If-Modified-Since' header.
* Zope responses '304 Not Modified' with the same Last-Modified value but without (updated) Cache-Control header.
* intermediate cache server does not (cannot) update its cache with updated cache configuration.

Thus cache inside intermediate cache server can stay forever, unless Zope returns a different Last-Modified value.

[RFC 7232](https://tools.ietf.org/html/rfc7232#section-4.1) says :

>   The server generating a 304 response MUST generate any of the
>   following header fields that would have been sent in a 200 (OK)
>   response to the same request: Cache-Control, Content-Location, Date,
>   ETag, Expires, and Vary.

With this PR, `_setCacheHeaders` is called before returning '304 Not Modified' so that intermediate cache can update its cache with updated Caching Policy Manager configuration.

2021-03-31 10:58 UTC, dataflake commented
Hi, please take a look at https://www.zope.org/developer/becoming-a-committer.html first and sign the contributor agreement. I'll be happy to look at the PR in detail once that's done and you're an official member in this GitHub organization.

2021-03-31 17:29 UTC, fdiary commented
> Hi, please take a look at https://www.zope.org/developer/becoming-a-committer.html first and sign the contributor agreement.

I just sent it.

2021-04-01 08:08 UTC, dataflake commented
@fdiary Did you follow the instruction "On page 2 enter Zope in the field for program"? The contributor admins made you a member of the `plonefoundation` organization but not `zopefoundation`?

2021-04-01 08:54 UTC, fdiary commented
> @fdiary Did you follow the instruction "On page 2 enter Zope in the field for program"? The contributor admins made you a member of the `plonefoundation` organization but not `zopefoundation`?

Yes I did... I'm asking now.

2021-04-01 17:35 UTC, dataflake approved these changes

2021-04-01 17:38 UTC, dataflake requested changes
Just noticed that this needs a change log entry as well.

2021-04-01 17:51 UTC, dataflake approved these changes
Thank you!

2021-04-01 17:51 UTC, merged